# Generated by Django 5.1.3 on 2024-12-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='book_appointment',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='book_appointment',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
