# Generated by Django 5.1.4 on 2024-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
